apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-web-deployment
spec:
  selector:
    matchLabels:
      run: student-web-deployment
  replicas: 1
  template:
    metadata:
      labels:
        run: student-web-deployment
    spec:
      containers:
      - name: hostping
        image: student-demo:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80